name: Arduino examples tests
on:
  push:
    paths:
      - 'tensorflow/**'
      - 'examples/*/*.robot'
      - 'examples/*/build.sh'
  pull_request:
    paths:
      - 'tensorflow/**'
      - 'examples/*/*.robot'
      - 'examples/*/build.sh'

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      GH_SERVICE_ACCOUNT_NAME: "tflite-bot"
      GH_SERVICE_ACCOUNT_EMAIL: "tflite-bot@antmicro.com"
      GH_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Configure git
        run: |
          git config --global user.name $GH_SERVICE_ACCOUNT_NAME
          git config --global user.email $GH_SERVICE_ACCOUNT_EMAIL
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Set Up Renode
        run: |
          wget https://dl.antmicro.com/projects/renode/builds/renode-latest.deb
          sudo apt install -y ./renode-latest.deb
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework==3.1 psutil pyyaml requests

      - name: Test person-detection
        run: |
          cd examples/person-detection
          ./build.sh
          renode-test *.robot

      - name: Upload person-detection artifacts
        uses: actions/upload-artifact@v2
        with:
          name: person_detection_artifacts
          path: |
            examples/person-detection/report.html
            examples/person-detection/log.html
            examples/person-detection/robot_output.xml
            examples/person-detection/person_detection.dump

      - name: Test magic-wand
        run: |
          cd examples/magic-wand
          ./build.sh
          renode-test *.robot

      - name: Upload magic-wand artifacts
        uses: actions/upload-artifact@v2
        with:
          name: magic_wand_artifacts
          path: |
            examples/magic-wand/report.html
            examples/magic-wand/log.html
            examples/magic-wand/robot_output.xml
            examples/magic-wand/*.dump

      - name: Test hello-world
        run: |
          cd examples/hello-world
          ./build.sh
          renode-test *.robot

      - name: Upload hello-world artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hello_world_artifacts
          path: |
            examples/magic-wand/report.html
            examples/magic-wand/log.html
            examples/magic-wand/robot_output.xml
            examples/magic-wand/*.dump

      - name: Upload binaries
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git clone https://github.com/antmicro/tensorflow-arduino-examples-binaries.git
          cp -r examples/*/binaries/* tensorflow-arduino-examples-binaries
          cd tensorflow-arduino-examples-binaries
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Upload binaries";
            git push -u https://$GH_SERVICE_ACCOUNT_NAME:$GH_SERVICE_ACCOUNT_TOKEN@github.com/antmicro/tensorflow-arduino-examples-binaries.git master
          else
            echo "no changes";
          fi
