name: Arduino examples tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      GH_SERVICE_ACCOUNT_NAME: "tflite-bot"
      GH_SERVICE_ACCOUNT_EMAIL: "tflite-bot@antmicro.com"
      GH_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
      METRICS_VISUALIZER: renode/tools/metrics_analyzer/metrics_visualizer/metrics-visualizer.py
      TENSORFLOW_PATH: "${{ github.workspace }}/tflite-micro"
    steps:
      - name: Configure git
        run: |
          git config --global user.name $GH_SERVICE_ACCOUNT_NAME
          git config --global user.email $GH_SERVICE_ACCOUNT_EMAIL
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Set Up Renode
        run: |
          mkdir -p renode
          cd renode
          wget https://dl.antmicro.com/projects/renode/builds/renode-latest.linux-portable.tar.gz
          tar -xzf renode-latest.linux-portable.tar.gz --strip 1
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/renode/tests/requirements.txt
          pip install -r $GITHUB_WORKSPACE/renode/tools/metrics_analyzer/metrics_visualizer/requirements.txt

      - name: Test person-detection
        run: |
          cd examples/person-detection
          ./build.sh
          $GITHUB_WORKSPACE/renode/test.sh *.robot
          mkdir graphs
          python $GITHUB_WORKSPACE/$METRICS_VISUALIZER person_detection.dump --no-dialogs -o graphs

      - name: Upload person-detection artifacts
        uses: actions/upload-artifact@v2
        with:
          name: person_detection_artifacts
          path: |
            examples/person-detection/report.html
            examples/person-detection/log.html
            examples/person-detection/robot_output.xml
            examples/person-detection/person_detection.dump
            examples/person-detection/graphs

      - name: Test magic-wand
        run: |
          cd examples/magic-wand
          ./build.sh
          $GITHUB_WORKSPACE/renode/test.sh *.robot
          mkdir ring_graphs
          python $GITHUB_WORKSPACE/$METRICS_VISUALIZER magic_wand_ring.dump --no-dialogs -o ring_graphs
          mkdir slope_graphs
          python $GITHUB_WORKSPACE/$METRICS_VISUALIZER magic_wand_slope.dump --no-dialogs -o slope_graphs

      - name: Upload magic-wand artifacts
        uses: actions/upload-artifact@v2
        with:
          name: magic_wand_artifacts
          path: |
            examples/magic-wand/report.html
            examples/magic-wand/log.html
            examples/magic-wand/robot_output.xml
            examples/magic-wand/*.dump
            examples/person-detection/ring_graphs
            examples/person-detection/slope_graphs

      - name: Test hello-world
        run: |
          cd examples/hello-world
          ./build.sh
          $GITHUB_WORKSPACE/renode/test.sh *.robot
          mkdir graphs
          python $GITHUB_WORKSPACE/$METRICS_VISUALIZER hello_world.dump --no-dialogs -o graphs

      - name: Upload hello-world artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hello_world_artifacts
          path: |
            examples/hello-world/report.html
            examples/hello-world/log.html
            examples/hello-world/robot_output.xml
            examples/hello-world/*.dump
            examples/person-detection/graphs

      - name: Test micro-speech
        run: |
          cd examples/micro-speech
          ./build.sh
          $GITHUB_WORKSPACE/renode/test.sh *.robot
          mkdir graphs
          python $GITHUB_WORKSPACE/$METRICS_VISUALIZER micro_speech.dump --no-dialogs -o graphs

      - name: Upload micro-speech artifacts
        uses: actions/upload-artifact@v2
        with:
          name: micro_speech_artifacts
          path: |
            examples/micro-speech/report.html
            examples/micro-speech/log.html
            examples/micro-speech/robot_output.xml
            examples/micro-speech/*.dump

      - name: Upload binaries
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git clone https://github.com/antmicro/tensorflow-arduino-examples-binaries.git
          cp -r examples/*/binaries/* tensorflow-arduino-examples-binaries
          cd tensorflow-arduino-examples-binaries
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Upload binaries";
            git push -u https://$GH_SERVICE_ACCOUNT_NAME:$GH_SERVICE_ACCOUNT_TOKEN@github.com/antmicro/tensorflow-arduino-examples-binaries.git master
          else
            echo "no changes";
          fi
