name: Arduino examples tests
on:
  push:
  pull_request:
    paths:
      - 'tensorflow'
      - 'tests'
      - 'build_binaries.sh'

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      GH_SERVICE_ACCOUNT_NAME: "tflite-bot"
      GH_SERVICE_ACCOUNT_EMAIL: "tflite-bot@antmicro.com"
      GH_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Configure git
        run: |
          git config --global user.name $GH_SERVICE_ACCOUNT_NAME
          git config --global user.email $GH_SERVICE_ACCOUNT_EMAIL
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binaries
        run: ./build_binaries.sh

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Set Up Renode
        run: |
          wget https://dl.antmicro.com/projects/renode/builds/renode-latest.deb
          sudo apt install -y ./renode-latest.deb
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework==3.1 psutil pyyaml requests

      - name: Test
        run: |
          cp -r binaries tests
          renode-test tests/**.robot

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: robot-output
          path: |
            report.html
            log.html
            robot_output.xml

      - name: Upload binaries
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git clone https://github.com/antmicro/tensorflow-arduino-examples-binaries.git
          cp -r binaries/person_detection tensorflow-arduino-examples-binaries
          cd tensorflow-arduino-examples-binaries
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Upload binaries";
            git push -u https://$GH_SERVICE_ACCOUNT_NAME:$GH_SERVICE_ACCOUNT_TOKEN@github.com/antmicro/tensorflow-arduino-examples-binaries.git master
          else
            echo "no changes";
          fi
